### ISSUE TITLE
BUG: Old position when onResizeStop is called

### ISSUE THREAD

**Issue by ifier** [bokuweb/react-rnd#565]
# Overview of the problem
I'm using react-rnd **version** [10.0.0]   
My **browser** is:   Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)
I am sure this issue is **not a duplicate**
   
### Reproduced project
https://codesandbox.io/s/sparkling-platform-v52np

### Description
I have enabled resizing by right and left sides.
I've dragged block along x axis to 50 ({ x: 50, y: 0 }). Then clicked (without changing width) on the right side (right trim control) and it gives me an old position - { x: 0, y: 0 }. The same with the left side.

But, if we have resized it a little bit (1px) and then release mouse button - it will return right position.

### Steps to Reproduce
1. Drag an element to some position along X axis
2. Click on the right/left trim control (without resize)
3. It will return an old position

### Expected behavior
It should always return new/current/correct position.
We dragged an element -> clicked on the left/right side without resize -> updated position should be in the param.

### Actual behavior
It returns an old position.

**Comment by willadamskeane** [comment]
Having this issue as well.

**Comment by Nickersona** [comment]
Hmm so I'm experiencing this as well. Haven't tested out any code yet, did a quick look in the code base to figure out  what might cause this.

Looks like: `onResizeStop` passes in the position from an instance prop `this. resizingPosition` which is only set in the `onResize` function but nowhere in the `onResizeStart`  function. So my thinking of why this isn't defined in the case of a single click, is that it RND only triggers `onResizeStart`  and `onResizeStop` in the case of a single click, which means that the `resizingPosition` is never defined, causing the callback to return the position as `{x: 0, y:0 }`

I noticed the same behaviour with the Drag events as well. The fix is probably easiest to just add the setting of `resizePosition` into the resize start, I'm just not sure if we'd have the correct position values at that point.

**Comment by GlynL** [comment]
just ran into this and appears to have been fixed.
#618 
#619
