### ISSUE TITLE
Static position for resize-only Rnd element

### ISSUE THREAD

**Issue by ruben00001** [bokuweb/react-rnd#844]
I want to have an `Rnd` element that can be resized (not dragged) that is positioned statically/relatively.

When I add `position: 'static'` to the `Rnd` element's `style`, the element gets `translated` in the y direction by its height. I've also disabled `transform` on the `react.draggable` class - this worked but also disabled the resize functionality.

Any suggestions?

Update:
Adding `position={{ x: 0, y: [initial height of Rnd element] }}` seems to have it working. This doesn't seem ideal though.

2nd Update:
Apologies, it's been a while but the above isn't reliable. I think @[dilizarov](https://github.com/dilizarov) solution below is the one to go for.

**Comment by ZambranoBeicker** [comment]
@ruben00001 I have the same problem. In my project we only need the resize feature but we're also using Styled Components. What i did was create a wrapper for Rnd component and overwrite the transform property. I didn't like it because I had to use `!important` to do so, but was the fastest solution I could find

**Comment by dilizarov** [comment]
@ZambranoBeicker been trying your method, but can't seem to strip the transform property - it's like it gets re-calced on every drag for me.

**Comment by dilizarov** [comment]
@ZambranoBeicker @ruben00001 I dug into the source code and turns out the perfect solution for me was to use the package re-resizable instead of this one.

This package uses re-resizable under the hood, but by using just that I don't get any of the dragging baggage that I need to account for. 

Cheers

**Comment by ruben00001** [comment]
> @ZambranoBeicker @ruben00001 I dug into the source code and turns out the perfect solution for me was to use the package re-resizable instead of this one.
> 
> This package uses re-resizable under the hood, but by using just that I don't get any of the dragging baggage that I need to account for.
> 
> Cheers

I think I ended up doing this too, but didn't realise this package uses re-resizable under the hood!

I'll close this issue now as I think this is a fine solution.
